### ISSUE TITLE
Rendering problems in android jellybean 4.1.2

### ISSUE THREAD

**Issue by AppDeveloperMax** [googlesamples/android-UniversalMusicPlayer#69] opened 2016-03-08 02:40 UTC
In the process of renderization in android studio i get some errors in this platform. Only in this platform but not in 2.3 or 5 and higher.

**Comment by mariusc83** [comment] 2016-03-15 21:04
One of the problems is caused by the IntroductorOverlay.java class when it tries to inflate the "ccl_intro_overlay.xml". I will try to add a pull request if I will be able to find a fix in the following days.

**Comment by naddaf** [comment] 2016-03-15 21:53
That is, probably, due to a bug in the compat library, the more recent one has addressed that; see https://github.com/googlecast/CastCompanionLibrary-android/issues/278

**Comment by AppDeveloperMax** [comment] 2016-03-17 02:56
I thinks this happen is the platform in my case is the jellybean 4.1.2 but not 4.2 or others :8ball:

**Comment by mariusc83** [comment] 2016-03-18 12:54
I've made a Pull Request by updating the Android Support to v23.2.1 and right now it should be compatible down to sdk 17.

**Comment by nic0lette** [comment] 2017-04-17 18:14
Given the support library has been updated a few times, I'm going to close this as obsolete. If it's still happening please feel free to reopen it.

**Closed by nic0lette** 2017-04-17 18:14 UTC
