### ISSUE TITLE
Unable to start receiver android.support.v4.media.session.MediaButtonReceiver

### ISSUE THREAD

**Issue by moon2009** [googlesamples/android-UniversalMusicPlayer#165] opened 2017-08-07 03:08 UTC
fhas a bug from farbic like this (device running Android 4.x):
Caused by java.lang.IllegalArgumentException: MediaButtonReceiver component may not be null.
       at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.(MediaSessionCompat.java)
       at android.support.v4.media.session.MediaSessionCompat.(MediaSessionCompat.java)
       at android.support.v4.media.session.MediaSessionCompat.(MediaSessionCompat.java)
       at com.zhulang.reader.audio.MusicService.onCreate(MusicService.java:162)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2756)
       at android.app.ActivityThread.access$1800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5322)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by nic0lette** [comment] 2017-10-19 03:00
Is this in the UAMP sample? Could you provide a full stack trace or steps to reproduce this?

**Comment by lsp19880926** [comment] 2018-06-07 02:43
i have the same problem 
Fatal Exception: java.lang.RuntimeException: Unable to create service com.xxx.module.musicplayer.MusicService: java.lang.IllegalArgumentException: MediaButtonReceiver component may not be null.
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2722)
       at android.app.ActivityThread.access$2100(ActivityThread.java:139)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1348)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5314)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by lsp19880926** [comment] 2018-06-07 07:48
MediaSessionImplBase：
```
   if (mbrComponent == null) {
                throw new IllegalArgumentException(
                        "MediaButtonReceiver component may not be null.");
            }
```
I find this code from MediaSessionCompat ,I register MediaButtonReceiver in AndroidManifest. 
There's a possibility that the device they are using is unable to get the broadcast receiver component for media button action registered in the manifest.

**Comment by nic0lette** [comment] 2018-06-07 16:29
Is it registered like this:

```
<receiver android:name="android.support.v4.media.session.MediaButtonReceiver" >
    <intent-filter>
        <action android:name="android.intent.action.MEDIA_BUTTON" />
    </intent-filter>
</receiver>
```

If it is, can you reproduce it using the code from the repo as is and provide a full stack trace?

**Comment by lsp19880926** [comment] 2018-06-08 14:32
I registered like this:
```
  <receiver android:name="android.support.v4.media.session.MediaButtonReceiver">
      <intent-filter>
        <action android:name="android.intent.action.MEDIA_BUTTON"/>
      </intent-filter>
    </receiver>
```
And it is working well  in most cases

For API 20 or earlier, Sometimes he can't work properly。

```
Fatal Exception: java.lang.RuntimeException: Unable to create service com.x xx.musicplayer.MusicService: java.lang.IllegalArgumentException: MediaButtonReceiver component may not be null.
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2580)
       at android.app.ActivityThread.access$1800(ActivityThread.java:135)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5019)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
       at dalvik.system.NativeStart.main(NativeStart.java)

Caused by java.lang.IllegalArgumentException: MediaButtonReceiver component may not be null.
       at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.(SourceFile)
       at android.support.v4.media.session.MediaSessionCompat.(SourceFile)
       at android.support.v4.media.session.MediaSessionCompat.(SourceFile)
       at com.xxx.MusicService.onCreate(SourceFile)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2570)
       at android.app.ActivityThread.access$1800(ActivityThread.java:135)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5019)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by nic0lette** [comment] 2018-06-08 14:45
But can you reproduce it with an unmodified copy of UAMP, cloned from this repo: https://github.com/googlesamples/android-UniversalMusicPlayer.git

It could be a bug in the support library, but I won't know for sure unless I can reproduce it myself, and to do that, I need to make sure that this code, without any changes, also produces the bug.

**Comment by lsp19880926** [comment] 2018-06-08 15:27
Thanks for your answer!
I think I see what you mean ，but  i can't  reproduce it.  
I found this bug from fabric (https://fabric.io)  which we used to collect bugs.
I can try to reproduce it with UAMP，if i do, i will provide a full stack trace.

**Comment by nic0lette** [comment] 2018-06-08 15:50
Ah, I see.

Take a look at this: https://b.corp.google.com/issues/37078913 There's a potential fix for this issue in comment 5 there (ie: call the other constructor for MediaSessionCompat and supply the explicit component name for your receiver).

However, if you're using the latest support library, you may also consider opening a new issue, since I think the team believes this issue is fixed.

**Comment by lsp19880926** [comment] 2018-06-22 03:57
I'm

**Comment by lsp19880926** [comment] 2018-06-22 06:05
I'm Sorry. I've been very busy recently.
 
 I can't open the link you provide , but i know i need call the other constructor.
 Is it possible for me to do this：
```
 ComponentName mbrComponent = new ComponentName(getApplicationContext().getPackageName(),
          MediaButtonReceiver.class.getName());
   MediaSessionCompat   mSession = new MediaSessionCompat(this, "MusicService", mbrComponent, null);
```

**Closed** 2018-08-13 13:53 UTC
Labels: obsolete
